### ISSUE TITLE
where to direct data deletion requests?

### ISSUE THREAD

**Issue by thatgim** [fiatjaf/njump#61]
Your platform is using and distributing my personal data against my explicit non-consent.
Where do I request permanent deletion?

**Comment by thatgim** [comment]
I added domain blocks for mostr.pub, fetch.mostr.net and momostr.pink but my data is still distributed by your platform.

Your delete link doesn't seem to do anything if I paste my profile URL.

This is a GDPR violation and I will report it to the authorities if not fixed. I will contact your hosters and service providers, too.

**Comment by dtonon** [comment]
Njump is just a Nostr client, like Damus, Amethyst, Coracle, Snort and dozens more; we are just showing data present on _public_ relays. As already explained you should ask them to remove your data.
Btw, you didn't answer my questions, so even if I could help you solve it directly (and I can't, as explained), without more information I couldn't give you any other suggestions either.

**Comment by gsovereignty** [comment]
>This is a GDPR violation and I will report it to the authorities if not fixed

We don't build things in a way that can be captured and controlled by parasites because although some of us are European we aren't cuck losers.

**Comment by melvincarvalho** [comment]
Do note that njump dot me, which is also the canonical link in njump and mirrors does silently send ip address and browsing history to spyware 3rd parties, without consent.  The other mirror nostr dot com did this too.

Not sure of the law on this, but it's an incredibly bad thing, and gives nostr a bad name

I generally consider njump to be pure spyware, but am hopeful it will get fixed in future.

This is one case where if the law were able to protect users in the nostr eco system, it would be an incredibly good thing.

**Comment by melvincarvalho** [comment]
> Njump doesn't store any data,

I think this is slightly misleading.  You know that njump dot me tracks and stores data.  Yet you still promote it:

![image](https://github.com/user-attachments/assets/6a94dd65-359f-4f44-a399-06b33c72427f)

![image](https://github.com/user-attachments/assets/2658ee32-5cdb-4081-ab2d-cefbfd2dcbd9)

Let's clean this up for the benefit of all the nostr users.

**Comment by melvincarvalho** [comment]
Why close this as completed?  

> Your platform is using and distributing my personal data against my explicit non-consent.

This is still outstanding!
