### ISSUE TITLE
njump preview formatting for Instagram DMs is broken

### ISSUE THREAD

**Issue by alltheseas** [fiatjaf/njump#69]
![image](https://github.com/user-attachments/assets/cd05a29e-c17c-4fe7-b15a-8e94e1f171b1)

https://njump.me/note1kzjl5essncqrgrfwp648dr6hv942uak7d2sa707wm7qytjhhgpjqmsj07s

**Comment by dtonon** [comment]
Fixed in a731bd27f508f83bb58ebcd5b7af340e4f4f252e.

![image](https://github.com/user-attachments/assets/bab61641-126e-42ef-9382-1982613d22fb)

Unfortunately, the solution is not perfect, due to the fact that Facebook and Instagram use the same bot to fetch the images, but they are somehow post-processed and visualized differently, and then cached (so used for both the platforms).
So the previous rendering happens if the link is first shared via Instagram DM. If it is shared first on Facebook, the following sharing on IG will render this half-broken version:

![image](https://github.com/user-attachments/assets/1895f197-3bcc-4ed1-bfcb-0c7bd23b3b70)
